### ISSUE TITLE
handle this scenario where underlying code runs my test in an async task?

### ISSUE THREAD

**Issue by raarts** [plataformatec/mox#16]
I have a problem testing an API Module, which in turn uses Tesla. My tests look like this:

```
# Because Tesla does not provide one, and we need it for mox
defmodule Behaviour.Tesla do
  @callback call(Tesla.Env.client, []) :: Tesla.Env.t
end

defmodule RapiWeb.MyAPITest do
  @moduledoc """
  Tests the API module
  """
  use RapiWeb.ConnCase
  import Plug.Conn, only: [put_req_header: 3]
  import Mox

  setup :verify_on_exit!

  setup %{conn: conn} do
    conn = put_req_header(conn, "content-type", "application/json")
    {:ok, %{conn: conn}}
  end

  test "MyAPI.token returns a token if the underlying service returns one" do
    TeslaMock
    |> expect(:call, fn env, _opts ->
      %{env | status: 200, body: Poison.encode!(
        %{
          token_type: "Bearer",
          access_token: "cHBtKbMDNdc3uX2LIhCy9eVwkodhEc87s6e5Fk0lRS",
          expires_in: 86400
        })
      }
    end)

    client = RapiWeb.Helpers.MyAPI.client("my.fakehost.com")
    result = RapiWeb.Helpers.MyAPI.token(client, "CLIENT_ID", "CLIENT_SECRET")

    response = elem(result, 1)
    token = response.body["access_token"]

    assert elem(result, 0) == :ok
    assert response.status == 200
    assert is_binary(token) and token != ""

  end
```

 All went well, until I added a timeout plug to Tesla and my test started to fail:

```
%Mox.UnexpectedCallError{message: "no expectation defined for TeslaMock.call/2 in process #PID<0.360.0>"}
  1) test MyAPI.token returns a token if the underlying service returns one (RapiWeb.MyAPITest)
     test/rapi_web/controllers/my_api_test.exs:71
     ** (Mox.UnexpectedCallError) no expectation defined for TeslaMock.call/2 in process #PID<0.360.0>
     code: result = RapiWeb.Helpers.MyAPI.token(client, "CLIENT_ID", "CLIENT_SECRET")
     stacktrace:
       (tesla) lib/tesla/middleware/timeout.ex:55: Tesla.Middleware.Timeout.repass_error/1
       (tesla) lib/tesla/middleware/timeout.ex:35: Tesla.Middleware.Timeout.call/3
       (tesla) lib/tesla/middleware/tuples.ex:41: Tesla.Middleware.Tuples.call/3
       test/rapi_web/controllers/my_api_test.exs:84: (test)
```

As it turns out, the Tesla timeout plug runs the request in an async task ([see here](https://github.com/teamon/tesla/blob/master/lib/tesla/middleware/timeout.ex#L27)).
I changed my test as suggested in the docs to:

```
  test "MyAPI.token returns a token if the underlying service returns one" do
    TeslaMock
    |> expect(:call, fn env, _opts ->
      %{env | status: 200, body: Poison.encode!(
        %{
          token_type: "Bearer",
          access_token: "cHBtKbMDNdc3uX2LIhCy9eVwkodhEc87s6e5Fk0lRS",
          expires_in: 86400
        })
      }
    end)

    parent_pid = self()
    Task.async(fn ->
      TeslaMock |> allow(parent_pid, self())

      client = RapiWeb.Helpers.MyAPI.client("my.fakehost.com")
      result = RapiWeb.Helpers.MyAPI.token(client, "CLIENT_ID", "CLIENT_SECRET")

      response = elem(result, 1)
      token = response.body["access_token"]

      assert elem(result, 0) == :ok
      assert response.status == 200
      assert is_binary(token) and token != ""
    end)
    |> Task.await
  end
```

But his does not help:

```
{%Mox.UnexpectedCallError{message: "no expectation defined for TeslaMock.call/2 in process #PID<0.4549.0>"}, [{Tesla.Middleware.Timeout, :repass_error, 1, [file: 'lib/tesla/middleware/timeout.ex', line: 55]}, {Tesla.Middleware.Timeout, :call, 3, [file: 'lib/tesla/middleware/timeout.ex', line: 35]}, {Tesla.Middleware.Tuples, :call, 3, [file: 'lib/tesla/middleware/tuples.ex', line: 41]}, {RapiWeb.MyAPITest, :"-test MyAPI.token returns a token if the underlying service returns one/1-fun-1-", 1, [file: 'test/rapi_web/controllers/my_api_test.exs', line: 88]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 85]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 36]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}
  1) test MyAPI.token returns a token if the underlying service returns one (RapiWeb.MyAPITest)
     test/rapi_web/controllers/my_api_test.exs:71
     ** (EXIT from #PID<0.4547.0>) an exception was raised:
         ** (Mox.UnexpectedCallError) no expectation defined for TeslaMock.call/2 in process #PID<0.4549.0>
             (tesla) lib/tesla/middleware/timeout.ex:55: Tesla.Middleware.Timeout.repass_error/1
             (tesla) lib/tesla/middleware/timeout.ex:35: Tesla.Middleware.Timeout.call/3
             (tesla) lib/tesla/middleware/tuples.ex:41: Tesla.Middleware.Tuples.call/3
             test/rapi_web/controllers/my_api_test.exs:88: anonymous fn/1 in RapiWeb.MyAPITest."test MyAPI.token returns a token if the underlying service returns one"/1
             (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

I guess if Tesla starts an async task to run my request in, that code has no access to the mock. 
Am I doing it wrong?

**Comment by josevalim** [comment]
You are correct. This will be possible when we finish #5, so please track that issue. Although that will mean those particular tests cannot run concurrently.
