### ISSUE TITLE
Mox application won't start on Elixir 1.4

### ISSUE THREAD

**Issue by take-five** [plataformatec/mox#25]
Although `mox` [depends on Elixir 1.4](https://github.com/plataformatec/mox/blob/master/mix.exs#L10), in reality it will work only with Elixir 1.5.

On Elixir 1.4, application crashes on start with error:
```
** (Mix) Could not start application mox: exited in: Mox.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            (elixir) lib/supervisor/spec.ex:169: anonymous fn/1 in Supervisor.Spec.supervise/2
            (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/supervisor/spec.ex:169: Supervisor.Spec.supervise/2
            (elixir) lib/supervisor.ex:297: Supervisor.start_link/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

I suppose, [this line](https://github.com/plataformatec/mox/blob/master/lib/mox/application.ex#L7) is the offender.

**Comment by josevalim** [comment]
Yup, you are right. We will bump the requirement to v1.5. Thank you.
